### ISSUE TITLE
`require('es6-promise')` installs a global polyfill?

### ISSUE THREAD

**Issue by tomekwi** [jakearchibald/es6-promise#144] opened 2015-09-22 12:11 UTC
Hi,

[the readme says otherwise](https://github.com/jakearchibald/es6-promise/tree/v3.0.2#auto-polyfill).

But I run into some [very weird problems](https://github.com/KenPowers/dr-promise/pull/1#issuecomment-142242614) – and it looks like it’s [`dist/es6-promise.js`](https://github.com/jakearchibald/es6-promise/blob/v3.0.2/dist/es6-promise.js#L926-L965) that causes them.

**Comment by tomekwi** [comment] 2015-09-22 12:14
Alright this is a dupe of #141.

**Comment by tomekwi** [comment] 2015-09-22 14:21
Hmm, reading through the OP at #141 and https://github.com/jakearchibald/es6-promise/issues/141#issuecomment-142299424 it looks like my this issue is a different thing after all.

@stefanpenner what I mean is that `require('es6-promise')` behaves unexpectedly like `require('es6-promise').polyfill()`.

Here’s some background: https://github.com/KenPowers/dr-promise/pull/1#issuecomment-142242614.

Here’s evidence:

Without `es6-promise`: http://jsbin.com/jezare/1/edit?html,js,console
With `es6-promise`: http://jsbin.com/jezare/2/edit?html,js,console

And here’s the source of the problem:  [`dist/es6-promise.js`](https://github.com/jakearchibald/es6-promise/blob/v3.0.2/dist/es6-promise.js#L926-L965).

**Comment by stefanpenner** [comment] 2015-09-22 14:41
The polyfil runs by default if the host has no promise, or the promise appears malformed. Chrome still ships a promise implementation with not bugs and it does not advertise itself correctly.

**Comment by tomekwi** [comment] 2015-09-22 16:32
> The polyfil runs by default if the host has no promise, or the promise appears malformed.

Then it wouldn’t hurt to document this. I spent well over 2 hours trying to find out what part of my toolchain causes this behavior.

> I will likely soon provide a two builds, which will allow the user to choose the level of compliance they care about.

There’s a great project by @ljharb *[es-shim-api](https://github.com/es-shims/es-shim-api)* – an attempt to keep this consistent across projects.

It comes with a tool to check compliance so that there are no more surpirizes. Something along the lines of *[standard](https://github.com/feross/standard)* but for polyfills.

**Comment by stefanpenner** [comment] 2015-09-22 17:29
closing this as a duplicate to #141

**Closed by stefanpenner** 2015-09-22 17:29 UTC

**Comment by tomekwi** [comment] 2015-09-22 21:04
Sorry if I misunderstand you – but it doesn’t seem like your comment https://github.com/jakearchibald/es6-promise/issues/141#issuecomment-142299424 addresses the issue I’ve raised here.

Perhaps I should open a new issue then – with more explicit wording? Or perhaps there already is an issue addressing the missing docs and missing equivalents ov [*es-shim-api*’s `.` and `/polyfill` entry point](https://github.com/es-shims/es-shim-api/tree/aa00b9865a14c12c0997d08bfb351c99f3bfe9ad#readme)?

**Comment by stefanpenner** [comment] 2015-09-22 21:15
the solution for that is to split the output, and give users what they expect. It becomes the callers choice as to the behavior.

**Comment by tomekwi** [comment] 2015-09-22 21:25
Alright :) I really hope we get rid of the ugly global side-effects :)

They don’t hurt that much if you’re developing an app – but when writing a library `require('es6-promise')` makes the whole thing unsafe.

**Comment by stefanpenner** [comment] 2015-09-22 22:38
> They don’t hurt that much if you’re developing an app – but when writing a library require('es6-promise') makes the whole thing unsafe.

Yes, but remember. This library was intended as a polyfil. Current it only smashes broken implementations, if that surprises you I am sorry.

It seems like people use it as library, so we will just provide two builds and let people use

**Comment by tomekwi** [comment] 2015-09-23 07:49
I really recommend https://github.com/es-shims/es-shim-api – a mouthful of good practices for developers of *polyfills*.

**Comment by tomekwi** [comment] 2015-09-23 08:37
But really thanks a lot for

>  will just provide two builds and let people use whichever they feel is important.

😃
