### ISSUE TITLE
Polyfill is always overring default Promise object

### ISSUE THREAD

**Issue by rlsoeiro** [jakearchibald/es6-promise#127] opened 2015-07-10 23:41 UTC
Hi,

I just tried to use the polyfill in Chrome (latest) and it is replacing the default implementation instead of properly detecting it.

The problem seems to be in this code fragment:
if (P && Object.prototype.toString.call(P.resolve()) === '[object Promise]' && !P.cast) {
    return;
}

Object.prototype.toString.call(P.resolve()) is returning '[object Object]'. Can anyone else reproduce this behavior? The fix should be simple, buit I'd like to know why this approach is being used to detect the default Promise.

**Comment by stefanpenner** [comment] 2015-07-11 00:27
> Object.prototype.toString.call(P.resolve()) is returning '[object Object]'. Can anyone else reproduce this behavior? The fix should be simple, buit I'd like to know why this approach is being used to detect the default Promise.

this version of chrome still has a bugy promise implementation, so we choose our implementation which does not suffer those same issues.

**Comment by stefanpenner** [comment] 2015-07-11 00:28
dupe of : https://github.com/jakearchibald/es6-promise/issues/111 and several others.

**Closed by stefanpenner** 2015-07-11 00:27 UTC
